### ISSUE TITLE
Add support for animated images

### ISSUE THREAD

**Issue by hugomassing** [meriadec/PixelartJS#3]
Hey, incredible tool here. Anyway, I was asking myself if there would by any way to animate generated images ? Some kind of "frames" definition (like passing an array of ascii instead of one), and possibility to set the delay between it? (and maybe a `loop` property).

Thanks for your work!

**Comment by meriadec** [comment]
It's fun cause I was actually talking about this with a friend.
Yeah, I agree, it must be on the launchpad now!

**Comment by Apercu** [comment]
:+1:

**Comment by hugomassing** [comment]
Thank you, you are very fast ;)
