### ISSUE TITLE
more open lisanse

### ISSUE THREAD

**Issue by DashLord3** [meriadec/PixelartJS#6]
hi,

i need to create a wordress w/t some drawings cubik style 4 my internship and my boss didnt agree to use pixefart caus of the restrictive lisance you set.
we dont really like open source and bsd is not good so can you pls at least change it to mit or else?

ty

**Comment by meriadec** [comment]
no

**Comment by DashLord3** [comment]
why m8? seriously shitty project and shitty owner. im gonna fork and set another lisance

**Comment by meriadec** [comment]
i will sue you and you will lose
go back to blender it's better for you

**Comment by DashLord3** [comment]
how do u even now wat im doing after school? fucking stalker, its me gonna soue u for abuse on minor
